kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: backend
  image: compose:1.25.0-rc2
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - up -f /drone/src/docker-compose-prod.yml -d --force-recreate


volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
  - NestJS-V2