kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: backend
  image: docker/compose
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose-prod.yml up --force-recreate -d caroneiro_api


volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
  - NestJS-V2