kind: pipeline
type: docker
name: default

# platform:
#   os: linux
#   arch: arm64

# workspace:
#   base: /go
#   path: src/github.com/caroneiroapp/app

steps:
# - name: backend
#   image: docker/compose
#   volumes:
#   - name: docker_sock
#     path: /var/run/docker.sock
#   commands:
#     - docker-compose -f docker-compose-prod.yml up --force-recreate -d caroneiro_api

# - name: build
#   image: docker
#   commands:
#     - docker build -t some/container .
#   volumes:
#     - name: docker_sock
#       path: /var/run/docker.sock

- name: deploy
  image: docker
  commands:
    - docker compose -f docker-compose-prod.yml up --force-recreate -d caroneiro_api
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock

services:
- name: docker:dind
  image: docker

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - NestJS-V2