version: '3'
services:
  caroneiro_api:
    container_name: caroneiro_api
    image: lucasferreira/caroneiroapp_api:latest
    # build: 
    #   context: ./caroneiro-api
    #   dockerfile: Dockerfile-production
    volumes:
      - './caroneiro-api:/caroneiro/api'
      - /caroneiro/api/node_modules
    ports:
      - '7000:7000'
    labels:
      - "traefik.backend=api-caroneiroapp"
      - "traefik.frontend.rule=Host:api.caroneiroapp.com.br"
      - traefik.port=7000
    networks:
      - web
      - docker-caroneiro

networks:
  web:
    external: true
  docker-caroneiro:
    external: false