version: '3'
services:
  caroneiro_api_local:
    container_name: caroneiro_api_local
    build: ./caroneiro-api
    volumes:
      - './caroneiro-api:/caroneiro/api_local'
      - /caroneiro/api_local/node_modules
    depends_on:
      - mongo
    ports:
      - '7500:7000'
    networks:
      - web

  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'Santos09021992'
    volumes:
      - './data/mongodb/db:/data/db'
    networks:
      - web

networks:
  web:
    external: true

volumes:
  mongodb_data:
    driver: local
