version: '3'
services:
  caroneiro_api:
    container_name: caroneiro_api
    build: 
      context: ./caroneiro-api
      dockerfile: Dockerfile-production
    volumes:
      - './caroneiro-api:/caroneiro/api'
      - /caroneiro/api/node_modules
    # depends_on:
    #  - mongo
    ports:
      - '7000:3000'
    labels:
      - "traefik.backend=api-caroneiroapp"
      - "traefik.frontend.rule=Host:api.cluster.caroneiroapp.com.br"
      - "traefik.port=7000"
    networks:
      - web
      - docker-caroneiro

networks:
  web:
    external: true
  docker-caroneiro:
    external: false