version: "3"
services:
 api:
   container_name: caroneiro-strapi-api
   build: ./caroneiro-api
   environment:
      - APP_NAME=caroneiro-api
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=localhost
      - DATABASE_PORT=27017
      - DATABASE_NAME=caroneirodb
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - HOST=localhost
   volumes:
     - ./caroneiro-api:/usr/src/api
     - /usr/src/api/node_modules
   depends_on:
     - mongo
   ports:
     - 1337:1337
   networks:
    - docker-caroneiro
   restart: always

 mongo:
   container_name: mongo
   image: mongo:latest
   ports:
     - 27017:27017
   volumes:
     - ./data/mongodb/db:/data/db
   networks:
    - docker-caroneiro

networks:
 docker-caroneiro:
   driver: bridge