FROM node:12
LABEL traefik.backend="api-caroneiroapp"
LABEL traefik.backend.rule="Host:api.cluster.caroneiroapp.com.br"
LABEL traefik.port="7000"
WORKDIR /caroneiro/api
COPY ./caroneiro-api/package.json package.json
# RUN npm install -g @nestjs/cli
RUN npm install
COPY ./caroneiro-api .
# RUN npm run build
CMD [ "npm", "run", "build" ]
# EXPOSE 7000
# CMD [ "npm", "run", "start:prod" ]