FROM node:12
#WORKDIR /caroneiro/api
COPY ./caroneiro-api/package.json package.json
# RUN npm install -g @nestjs/cli
RUN npm install --production
COPY ./caroneiro-api .
RUN npm run build
EXPOSE 7000
CMD [ "npm", "run", "start:prod" ]