FROM node:10.16.3-slim
RUN apt-get update -y && apt-get install -y build-essential && apt-get install -y python && \
  npm install -g prebuild-install node-pre-gyp node-gyp
WORKDIR /caroneiro/api
COPY ./caroneiro-api/package.json /caroneiro/api/package.json
# RUN npm uninstall bcrypt && npm install bcrypt@3.0.6
RUN npm install --production
COPY ./caroneiro-api /caroneiro/api
RUN npm run build
EXPOSE 7000
CMD [ "npm", "run", "start:prod" ]